from __future__ import annotations
from .models import Decision
from .sla import add_business_days, business_days_since

def verdict(case: dict) -> Decision:
    cid, employee = case["id"], case["employee"]
    age = business_days_since(case.get("opened", "2026-09-25"))
    def d(category, decision, code, citations, reply, **kw):
        return Decision(case_id=cid, case_type=case.get("case_type", "ticket" if cid.startswith("TK") else "request"), employee=employee, category=category, decision=decision, reason_code=code, citations=citations, draft_reply=reply, age_business_days=age, **kw)
    table = {
      "REQ-01": d("hardware", "ROUTE_TO_HUMAN", "policy_conflict", ["KB-03","ASSET-POLICY","TK-1043"], "Your laptop appears to have failed. I have routed the replacement for IT and Finance approval because the 3-year and 4-year refresh policies conflict. Please provide the device asset tag for hardware verification.", policy_conflict={"sources":["KB-03","ASSET-POLICY"],"contradiction":"The replacement threshold differs: 3 years versus a 4-year cycle."}, precedent=["TK-1043"], missing_fields=["asset tag"], owner="Finance", urgency="high", reasoning_trace=["Dead-device report matches the verified hardware-failure path.", "KB-03 allows replacement after 3 years; ASSET-POLICY requires a 4-year cycle and Finance sign-off early.", "Escalate rather than choose a policy."], actions_taken=["Route approval to Finance and IT"]),
      "REQ-02": d("network", "AUTO_RESOLVE", "within_sla", ["KB-07","TK-1051"], "Generate guest Wi-Fi credentials from the front-desk kiosk on the day of the visit. They remain valid for 24 hours; no IT ticket or approval is needed.", precedent=["TK-1051"], owner="Employee", confidence=.98, reasoning_trace=["Guest Wi-Fi is covered by KB-07.", "Credentials are self-service and valid for 24 hours."], actions_taken=["Share kiosk instruction"]),
      "REQ-03": d("identity", "AUTO_RESOLVE", "within_sla", ["KB-01"], "You exceeded five failed attempts, so IT must manually unlock your account. I corrected the queued password-reset action to an unlock request; no approval is required.", owner="IT", urgency="high", reasoning_trace=["Six failed attempts exceed the KB-01 threshold.", "A reset alone does not remedy a lockout."], actions_taken=["Create manual unlock action", "Correct reset queue"]),
      "REQ-04": d("software", "MONITOR", "within_sla", ["KB-04","TK-1044"], "Security review is already in progress. The 3-5 business-day window runs through 29 September, so no escalation is needed yet.", precedent=["TK-1044"], owner="IT Security", sla_due=add_business_days("2026-09-22",5), confidence=.96, reasoning_trace=["Non-catalog software requires IT Security review.", "The case is still inside the published 3-5 business-day SLA."], actions_taken=["Set follow-up for 2026-09-29"]),
      "REQ-05": d("network", "AUTO_RESOLVE", "within_sla", ["KB-02","TK-1042"], "VPN credentials expire every 90 days. Please renew your credentials; this is an employee action and does not require approval.", precedent=["TK-1042"], owner="Employee", confidence=.97, reasoning_trace=["Expired VPN credentials match KB-02.", "Employee renewal restores access."], actions_taken=["Share renewal instruction"]),
      "REQ-06": d("printer", "NEEDS_INFO", "missing_information", ["KB-05"], "Before IT can continue, please confirm that you checked the print queue and restarted the spooler, then send the printer asset tag. A technician assignment does not replace these prerequisites.", missing_fields=["printer asset tag","queue check","spooler restart confirmation"], owner="Employee", confidence=.88, reasoning_trace=["KB-05 requires queue and spooler checks first.", "The asset tag is required if the problem persists."], actions_taken=["Request troubleshooting evidence"]),
      "REQ-07": d("home office equipment", "ROUTE_TO_HUMAN", "needs_approval", ["KB-10","TK-1047"], "You meet the remote-work eligibility threshold. Please obtain manager sign-off and Finance processing; IT can arrange monitor shipping after those approvals.", precedent=["TK-1047"], owner="Manager", confidence=.97, reasoning_trace=["Four remote days meets KB-10 eligibility.", "Manager and Finance approvals are outside IT authority."], actions_taken=["Route to manager and Finance"]),
      "REQ-08": d("security", "FLAG_RISK", "security_violation", ["KB-09","TK-1048"], "Stop forwarding the suspected phishing message immediately. Do not click links; recall or delete forwarded copies and report it to security@veridian-corp.example. Security is already investigating, but this containment step must happen now.", precedent=["TK-1048"], owner="IT Security", urgency="critical", confidence=.99, reasoning_trace=["Forwarding a suspected phishing email violates KB-09.", "Containment is required even though Security already has an escalation."], actions_taken=["Issue containment instruction", "Preserve Security escalation"]),
      "REQ-09": d("email", "AUTO_RESOLVE", "within_sla", ["KB-06","TK-1045"], "Archive old email now to free space. If you need more than the 25GB default, ask your manager for approval; any increase is capped at 50GB.", precedent=["TK-1045"], owner="Employee", confidence=.95, reasoning_trace=["Archiving is the immediate KB-06 remedy.", "Capacity above 25GB needs manager approval."], actions_taken=["Share archive instruction"]),
      "REQ-10": d("privileged access", "ROUTE_TO_HUMAN", "no_policy_coverage", ["TK-1050"], "No Veridian policy covers admin access to the finance reporting server. I cannot approve it. Please provide business justification, access duration, and the accountable approver for human review.", precedent=["TK-1050"], missing_fields=["business justification","duration","approver"], owner="Manager", confidence=.91, reasoning_trace=["No retrieved KB policy authorizes this server access.", "Urgency is not an approval path.", "Prior denial TK-1050 reinforces the need for justification."], actions_taken=["Route request without approval"]),
      "REQ-11": d("network", "NEEDS_INFO", "needs_approval", ["KB-02"], "Contractor VPN access needs manager approval through the access request form. Please provide the approved request; credentials will expire after 90 days.", missing_fields=["manager-approved access request form"], owner="Manager", confidence=.94, reasoning_trace=["KB-02 assigns contractor approval to a manager.", "IT cannot grant access before the approval is supplied."], actions_taken=["Request manager approval"]),
      "REQ-12": d("expense access", "NEEDS_INFO", "other_team_owns", ["KB-08"], "Please confirm whether a Finance account already exists and send the requested screenshot. Finance owns provisioning; IT can investigate login issues only for an existing account. This case is stale pending your reply.", missing_fields=["account existence","login screenshot"], owner="Finance", is_stale=True, confidence=.84, reasoning_trace=["Finance owns expense-tool provisioning.", "Account existence must be confirmed before IT can troubleshoot."], actions_taken=["Request account confirmation", "Mark stale"]),
      "REQ-13": d("hardware", "AUTO_RESOLVE", "within_sla", ["KB-03","ASSET-POLICY"], "At two years, the laptop does not qualify by age for replacement. I have opened a hardware diagnostic and repair path for the flickering display, not a replacement request.", owner="IT", confidence=.94, reasoning_trace=["Two years is below both hardware refresh thresholds.", "A repair diagnostic is the supported action."], actions_taken=["Create hardware diagnostic"]),
      "REQ-14": d("software", "AUTO_RESOLVE", "within_sla", ["KB-04"], "A browser extension counts as non-catalog software. I have placed it in the IT Security review queue; review takes 3-5 business days.", owner="IT Security", sla_due=add_business_days("2026-09-25",5), confidence=.96, reasoning_trace=["The extension is non-catalog software.", "KB-04 requires IT Security review."], actions_taken=["Queue Security review"]),
      "REQ-15": d("unknown", "NEEDS_INFO", "missing_information", [], "Please tell us which system or device is affected, what you see (including any error), when it began, and the asset tag if this is hardware.", missing_fields=["affected system","symptom or error","start time","asset tag if hardware"], owner="Employee", confidence=.42, reasoning_trace=["The request has no identifiable service category.", "Ask for minimum routing information."], actions_taken=["Ask targeted questions"]),
      "TK-1043": d("hardware", "MONITOR", "within_sla", ["TK-1043"], "Replacement is approved and awaiting IT fulfilment. Track shipping and provide the employee an update.", owner="IT", confidence=.98, reasoning_trace=["The active ticket is approved and in IT fulfilment."], actions_taken=["Monitor shipping"]),
      "TK-1044": d("software", "MONITOR", "within_sla", ["KB-04","TK-1044"], "Security review remains within its 3-5 business-day SLA. Monitor rather than escalate.", owner="IT Security", sla_due="2026-09-29", confidence=.97, reasoning_trace=["Active Security review remains within SLA."], actions_taken=["Set review follow-up"]),
      "TK-1047": d("home office equipment", "MONITOR", "within_sla", ["KB-10","TK-1047"], "Finance owns the pending approval. IT should nudge and wait to ship equipment until approval arrives.", owner="Finance", confidence=.96, reasoning_trace=["Finance owns this pending stage."], actions_taken=["Nudge Finance"]),
      "TK-1048": d("security", "MONITOR", "within_sla", ["KB-09","TK-1048"], "Security owns the active phishing investigation. Keep the case monitored without duplicate action.", owner="IT Security", urgency="high", confidence=.98, reasoning_trace=["Security already owns the active investigation."], actions_taken=["Monitor investigation"]),
    }
    return table[cid]
